### ISSUE TITLE
Improvements of Connector wizard

### ISSUE THREAD

**Issue by jg-gatech** [jg-gatech/eCableDesigner#13]
See Balsamiq wireframe 2.6 showing the connector wizard here: https://balsamiq.cloud/s2m0iqy/pvvkrcx/r4F8A

Also see the explanation of this wireframe here: https://screencast-o-matic.com/watch/cq6TDVudMp

**Comment by msarvank** [comment]
<img width="330" alt="ConnectorWizard" src="https://user-images.githubusercontent.com/8958836/68391083-c7f51b80-018c-11ea-9721-7378063d6c27.png">

**Comment by cmalai** [comment]
Implementation moved to TitleAreaDialog.

**Comment by msarvank** [comment]
![image](https://user-images.githubusercontent.com/8958836/68674200-6c0b0800-057b-11ea-9d58-5b2514a7dff7.png)

**Comment by msarvank** [comment]
Contacts under connector wizard should not be sorted. It should be displayed as per the serial number.

**Comment by msarvank** [comment]
![image](https://user-images.githubusercontent.com/8958836/68871409-63086b00-0722-11ea-9269-e32ce7a0d9f3.png)

**Comment by msarvank** [comment]
![image](https://user-images.githubusercontent.com/8958836/68871471-7d424900-0722-11ea-83bc-2ca278132313.png)

**Comment by jg-gatech** [comment]
Build 20191122 has not fixed the problem that the user cannot type in a number of contacts.

**Comment by msarvank** [comment]
Remove the default contact and make it undefined

**Comment by msarvank** [comment]
![image](https://user-images.githubusercontent.com/8958836/69783140-e02ee800-11d8-11ea-8764-235528f7746e.png)

**Comment by jg-gatech** [comment]
The problem as we discussed yesterday is that "0" is a defined value. But the value should be undefined; it should be blank.

**Comment by cmalai** [comment]
Widget used is a Spinner. Its default value is 0.
Otherwise we will have to move to Text Box and whenever focus is lost on the TextBox we will have to create the Contacts.

Lets discuss in the next meeting

**Comment by jg-gatech** [comment]
I think a text box is a good solution, because most connectors have too many contacts to use the spinner to enter the number.

Currently, if the user enters the number of contacts or uses the spinner to increment the number of contacts, then presses Enter, the wizard closes. Because focus in on the Create button, pressing Enter while in the spinner creates the connector. But Enter should cause the value to be accepted, then allow the user to continue editing in the wizard.

**Comment by msarvank** [comment]
Recommended to be moved as a new task in month 2

**Comment by jg-gatech** [comment]
New task #61 added.
