### ISSUE TITLE
Library component Add menu.

### ISSUE THREAD

**Issue by jg-gatech** [jg-gatech/eCableDesigner#3]
To add a component to a library folder, r-click the folder and select Add. The Add menu is shown in Balsamiq wireframe 2.1 here: https://balsamiq.cloud/s2m0iqy/pvvkrcx/r1FB3

**Comment by msarvank** [comment]
Move Connector and Cable wizard into model element under the add menu

**Comment by msarvank** [comment]
![image](https://user-images.githubusercontent.com/8958836/68945533-9c021780-07d6-11ea-9c03-495905275ec3.png)

**Comment by msarvank** [comment]
![image](https://user-images.githubusercontent.com/8958836/69222882-5d86a700-0ba0-11ea-87c3-f51afce3d677.png)

**Comment by msarvank** [comment]
Add terminal and connection placeholder into add submenu

**Comment by jg-gatech** [comment]
Please add Attachment as shown here: https://balsamiq.cloud/s2m0iqy/pvvkrcx/r1FB3.

**Comment by jg-gatech** [comment]
Change "Folders Folder" to "Folder". If I create a folder in a library, it shows "Folders Folder". But if I create a folder in a folder, it shows "Folder", as it should.
![folder](https://user-images.githubusercontent.com/36635136/69923724-afff7780-146c-11ea-8b45-ba62292e2f63.png)
