### ISSUE TITLE
Contact and Connector type

### ISSUE THREAD

**Issue by jg-gatech** [jg-gatech/eCableDesigner#33]
The field for Contact Type (Pin, Socket) or Connector Type (Plug, Receptacle, Symmetric) should be blank by default, and a value is not required. Blank means that it is undefined. See wireframe 2.5, https://balsamiq.cloud/s2m0iqy/pvvkrcx/rCF36

**Comment by cmalai** [comment]
Contact Type and Connector Type are set thru an Enumeration Object.
Therefore they cannot be marked blank but can be marked as UNDEFINED.
We would require to update the model to make the default value as UNDEFINED

**Comment by msarvank** [comment]
![image](https://user-images.githubusercontent.com/8958836/68945647-dec3ef80-07d6-11ea-8bc0-8255e7ebf6f1.png)

**Comment by msarvank** [comment]
![image](https://user-images.githubusercontent.com/8958836/68945682-f0a59280-07d6-11ea-882d-984ec75e8540.png)
