### ISSUE TITLE
"Show in BOM" attribute

### ISSUE THREAD

**Issue by jg-gatech** [jg-gatech/eCableDesigner#39]
In the Library and in the Design, all components should have "Show in BOM" set to True by default except for:
1. Contacts in a connecctor.
2. Connectors in a black box.
For these two exceptions, "Show in BOM" should default to False.

**Comment by cmalai** [comment]
**Proposed Implementation**
If a Connector is created using >> Right Clicks on AVIONICS and selects the Connector Wizard
Then the "Show in BOM" attribute 
1. Connector Object 
2. Contacts created under that Connector 
are set to False.

**Comment by msarvank** [comment]
Contacts are created via connector wizard:
1. Contacts in table shows as false but after creation it is marked as true.

**Comment by msarvank** [comment]
![image](https://user-images.githubusercontent.com/8958836/68870484-f771ce00-0720-11ea-8bbc-7636f5373be5.png)

**Comment by msarvank** [comment]
![image](https://user-images.githubusercontent.com/8958836/68870640-33a52e80-0721-11ea-975d-a2f1fc47fd46.png)
