### ISSUE TITLE
Company name misspelled

### ISSUE THREAD

**Issue by jg-gatech** [jg-gatech/eCableDesigner#41]
Following is the header of the library file, which shows that the company name is spelled two ways. "Kronotek" is the correct spelling, "kronotec" should be corrected. Check to ensure that the wrong spelling does not appear elsewhere.

<?xml version="1.0" encoding="UTF-8"?>
<ecadlib:Library xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecadlib="https://kronotec.com/ecad/library" xmlns:ecd="http://kronotek.com/ecabledesigner" xmi:id="_1OfO4IOYEemAuqRl1SxumQ" name="0531.ecdlib">

**Comment by msarvank** [comment]
Ecadlib should be chnaged into ecdlib
<?xml version="1.0" encoding="UTF-8"?>
<ecadlib:Library xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ecadlib="https://kronotek.com/ecad/library" name="Testecdlibrary.ecdlib">
  <folders/>
</ecadlib:Library>

**Comment by msarvank** [comment]
In contact object name should be renamed as id and serial number field to be added

**Comment by msarvank** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<ecd:ECableRoot xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ecd="http://kronotek.com/ecabledesigner" xmi:id="_Ng9n0AcNEequbON5OGG1Ew">
  <model xmi:id="_Ng9n0QcNEequbON5OGG1Ew">
    <signals xmi:id="_Ng9n0gcNEequbON5OGG1Ew"/>
    <blackBoxes xmi:id="_Ng9n0wcNEequbON5OGG1Ew"/>
  </model>
</ecd:ECableRoot>
