### ISSUE TITLE
Conductor attach point

### ISSUE THREAD

**Issue by jg-gatech** [jg-gatech/eCableDesigner#5]
A black box may have connectors, which require a mating connector to attach to it. But a black box may have 0..* (zero to many) conductor attach points. A conductor attach point allows a conductor to be connected without a mating connector. For example, the power supply in the image below has seven screw terminals which allow conductors to be attached without a mating connector.
![image](https://user-images.githubusercontent.com/36635136/67536027-daeef280-f69a-11e9-8ac8-266afda2ed10.png)

**Comment by msarvank** [comment]
Black box should allow to create multiple conductor attach points

**Comment by msarvank** [comment]
Black box should allow to create multiple conductor attach points

**Comment by msarvank** [comment]
Change the name of black box conductor attach point to conductor attach point

**Comment by msarvank** [comment]
Remove the default value of eobject

**Comment by jg-gatech** [comment]
1. After creating a Conductor Attach Point on a black box, it appears as "Abstract Aggregator".
2. When I rename the Conductor Attach Point in the Properties window, I get the error shown below.
![image](https://user-images.githubusercontent.com/36635136/70007760-32ed0480-1537-11ea-94f4-0e4af7c3dc90.png)
3. I cannot rename the Conductor Attach Point in the tree editor using click+click.
