### ISSUE TITLE
Implement the UI changes recommended by Patrick Paulin

### ISSUE THREAD

**Issue by jg-gatech** [jg-gatech/eCableDesigner#50]
1. Remove perspectives from the UI
2. Remove Eclipse Resource Framework
3. Remove unwanted UI contributions for included features

See docs/Patrick Paulin recommendations 20191013.pdf for details.

**Comment by msarvank** [comment]
1. ECable Designer perspective added
2. Open design & library toolitem added
3. New design and library toolitem added
4. Properties view added into perspective.
5. Connectors and Contacts view added into perspective
<img width="961" alt="ecabledesigner" src="https://user-images.githubusercontent.com/8958836/68392619-266fc900-0190-11ea-9c24-f12924370f16.png">
