### ISSUE TITLE
Add a library search function which allows user to enter part of an attribute to find a component

### ISSUE THREAD

**Issue by jg-gatech** [jg-gatech/eCableDesigner#9]
For example, if a user enters a portion of the part number, all components with that string in one of the attributes will be shown.

**Comment by cmalai** [comment]
Tree Search will be based on Mandatory Field : name.

**Comment by msarvank** [comment]
![image](https://user-images.githubusercontent.com/8958836/69858065-3b370c80-12b7-11ea-88a5-7055390d8a9c.png)
